name: Update versions

on:
  workflow_dispatch:
  schedule:
    - cron: "30 10,19 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts"
      - run: node updateVersions.mjs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
