name: Update versions

on:
  workflow_dispatch:
  schedule:
    - cron: "30 10,19 * * *" # Runs at 10:30 and 19:30 UTC. 

permissions:
  contents: write
  pull-requests: write

jobs:
  update-versions:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: './updateVersions/'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install node dependencies
        run: npm install
      - run: node updateVersions.mjs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
